title: UO Public Cloud Wiki
description: Helpful documentation about public cloud usage for UO customers
theme: just-the-docs

url: https://uo-aws-lza.github.io/docs

aux_links:
  UofO: https://uoregon.edu
  Request Support: https://service.uoregon.edu
  Source: https://github.com/uo-aws-lza
